<?php

$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['imageoptimizer'] = [
    'debug' => '0',
    'gifBinary' => 'gifsicle',
    'gifCheck' => 'gif',
    'gifOnProcessing' => '0',
    'gifOnUpload' => '0',
    'gifParametersOnProcessing' => '--batch -O2 %s',
    'gifParametersOnUpload' => '--batch -O2 %s',
    'jpgBinary' => 'jpegoptim',
    'jpgCheck' => 'jpg',
    'jpgOnProcessing' => '0',
    'jpgOnUpload' => '0',
    'jpgParametersOnProcessing' => '--strip-all %s',
    'jpgParametersOnUpload' => '--strip-all %s',
    'pngBinary' => 'optipng',
    'pngCheck' => 'png',
    'pngOnProcessing' => '0',
    'pngOnUpload' => '0',
    'pngParametersOnProcessing' => '-o2 %s',
    'pngParametersOnUpload' => '-o2 %s',
    'svgBinary' => 'svgo',
    'svgCheck' => 'svg',
    'svgOnUpload' => '0',
    'svgParametersOnUpload' => '--pretty %s',
];
