#!/bin/bash

activeString=""
action=$(echo "enable\ndisable\n" | $dmenu -i -p "$activeString")
case "$action" in
"enable")
    sudo /bin/ln -s /etc/php/5.6/mods-available/xdebug.ini /etc/php/5.6/cli/conf.d/20-xdebug.ini
    sudo /bin/ln -s /etc/php/5.6/mods-available/xdebug.ini /etc/php/5.6/fpm/conf.d/20-xdebug.ini

    sudo /bin/ln -s /etc/php/7.0/mods-available/xdebug.ini /etc/php/7.0/cli/conf.d/20-xdebug.ini
    sudo /bin/ln -s /etc/php/7.0/mods-available/xdebug.ini /etc/php/7.0/fpm/conf.d/20-xdebug.ini

    sudo /bin/ln -s /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/cli/conf.d/20-xdebug.ini
    sudo /bin/ln -s /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/fpm/conf.d/20-xdebug.ini

    sudo /bin/ln -s /etc/php/7.2/mods-available/xdebug.ini /etc/php/7.2/cli/conf.d/20-xdebug.ini
    sudo /bin/ln -s /etc/php/7.2/mods-available/xdebug.ini /etc/php/7.2/fpm/conf.d/20-xdebug.ini

    sudo /bin/ln -s /etc/php/7.3/mods-available/xdebug.ini /etc/php/7.3/cli/conf.d/20-xdebug.ini
    sudo /bin/ln -s /etc/php/7.3/mods-available/xdebug.ini /etc/php/7.3/fpm/conf.d/20-xdebug.ini

    sudo /bin/ln -s /etc/php/7.4/mods-available/xdebug.ini /etc/php/7.4/cli/conf.d/20-xdebug.ini
    sudo /bin/ln -s /etc/php/7.4/mods-available/xdebug.ini /etc/php/7.4/fpm/conf.d/20-xdebug.ini

    sudo /bin/ln -s /etc/php/8.0/mods-available/xdebug.ini /etc/php/8.0/cli/conf.d/20-xdebug.ini
    sudo /bin/ln -s /etc/php/8.0/mods-available/xdebug.ini /etc/php/8.0/fpm/conf.d/20-xdebug.ini
    ;;
"disable")
    sudo /usr/bin/unlink /etc/php/5.6/cli/conf.d/20-xdebug.ini
    sudo /usr/bin/unlink /etc/php/5.6/fpm/conf.d/20-xdebug.ini

    sudo /usr/bin/unlink /etc/php/7.0/cli/conf.d/20-xdebug.ini
    sudo /usr/bin/unlink /etc/php/7.0/fpm/conf.d/20-xdebug.ini

    sudo /usr/bin/unlink /etc/php/7.1/cli/conf.d/20-xdebug.ini
    sudo /usr/bin/unlink /etc/php/7.1/fpm/conf.d/20-xdebug.ini

    sudo /usr/bin/unlink /etc/php/7.2/cli/conf.d/20-xdebug.ini
    sudo /usr/bin/unlink /etc/php/7.2/fpm/conf.d/20-xdebug.ini

    sudo /usr/bin/unlink /etc/php/7.3/cli/conf.d/20-xdebug.ini
    sudo /usr/bin/unlink /etc/php/7.3/fpm/conf.d/20-xdebug.ini

    sudo /usr/bin/unlink /etc/php/7.4/cli/conf.d/20-xdebug.ini
    sudo /usr/bin/unlink /etc/php/7.4/fpm/conf.d/20-xdebug.ini

    sudo /usr/bin/unlink /etc/php/8.0/cli/conf.d/20-xdebug.ini
    sudo /usr/bin/unlink /etc/php/8.0/fpm/conf.d/20-xdebug.ini
    ;;
*)
    exit 0
    ;;
esac

sudo /bin/systemctl reload php5.6-fpm.service
sudo /bin/systemctl reload php7.0-fpm.service
sudo /bin/systemctl reload php7.1-fpm.service
sudo /bin/systemctl reload php7.2-fpm.service
sudo /bin/systemctl reload php7.3-fpm.service
sudo /bin/systemctl reload php7.4-fpm.service
sudo /bin/systemctl reload php8.0-fpm.service
pkill -SIGRTMIN+10 i3blocks
notify-send "switching xdebug: $action"
